services:
  cloud-provider:
    build: .
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - kind
    environment:
      - DDCP_DOCKER_NETWORK=kind
      - DDCP_SKIP_LOADBALANCER_READINESS_CHECK=true
    # (Opcional) nombre fijo para inspeccionar f√°cilmente
    container_name: desktop-cloud-provider

networks:
  kind:
    external: true
    name: kind